CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_name TEXT NOT NULL,
    email VARCHAR,
    password CHAR(60),
    created TIMESTAMP DEFAULT now() NOT NULL,
    UNIQUE (user_name)
);